# Generated by Django 4.0.1 on 2022-05-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название статьи')),
                ('text', models.TextField(max_length=200000, verbose_name='Текст статьи')),
                ('author', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание статьи')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликованно')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
